[book]
description = "A unique edition of a published work"

[book.fields]
title = { type = "str" }
blurb = { type = "str" }
isbn = { type = "str" }
language = { type = "str" }

[book_creatorship]
description = "An instance of someone contributing to a book's creation"

[book_creatorship.fields]
name = { type = "str" }
role = { type = "str" }

[book_item]
description = "A specific instance of a physical book"

[book_item.fields]