[book]
description = "A unique edition of a published work"

[book.fields]
title = { type = "str" }
subtitle = { type = "str" }
blurb = { type = "str" }
isbn = { type = "str" }
language = { type = "str" }

[book_creator]
description = "An instance of someone contributing to a book's creation"

[book_creator.fields]
name = { type = "str" }
role = { type = "str" }
