[book]
description = "A unique published work"

[book.fields]
name = { type = "str" }
address = { type = "str" }
opening_year = { type = "int" }

[book_edition]
description = "An edition of a published work"

[book_edition.fields]
format = { type = "str" }
isbn = { type = "str" }

[book_item]
description = "A specific instance of a physical book"

[book_item.fields]